# Generated by Django 2.2.16 on 2023-01-12 13:14

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20230112_1458'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_follow_yourself',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='no_follow_yourself'),
        ),
    ]
